<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IsPublishable>True</IsPublishable>
    <ErrorReport>none</ErrorReport>
    <AssemblyVersion>4.8.0.0</AssemblyVersion>
    <FileVersion>4.8ta.0.0</FileVersion>
    <AssemblyInformationalVersion>4.8.0.0</AssemblyInformationalVersion>
    <ProductVersion>4.8.0.0</ProductVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="meet\GetSomeData.cs" />
    <Compile Remove="meet\RibbonProcessor.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="PluginUiThumb.jpg" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="PluginUiThumb.jpg" />
  </ItemGroup>
  <ItemGroup>
    <None Include="meet\GetSomeData.cs" />
    <None Include="meet\RibbonProcessor.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.8.2" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
	  <PackageReference Include="SkiaSharp" Version="2.88.6" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;%25AppData%25\Emby-Server\programdata\plugins\&quot;" />
  </Target>

</Project>